#!/usr/bin/env bash
set -e
set -u

# this is to support running Renode from external directory
ROOT_PATH="$(cd $(dirname $0); echo $PWD)"

. "$ROOT_PATH/tools/common.sh"

OUTPUT_PATH="$ROOT_PATH/output/bin"

TARGET="Release"
QUIET=false

PARAMS=()
while [[ "$#" -gt 0 ]]
do
    case $1 in
    -d|--debug)
        TARGET="Debug"
        LAUNCHER="$LAUNCHER --debug"
        ;;
    -q|--quiet)
        QUIET=true
        ;;
    *)
        PARAMS+=("$1")
        ;;
    esac
    shift
done

verify_mono_version

if ${REMOTE:-false}
then
    LAUNCHER="$LAUNCHER --debugger-agent=transport=dt_socket,address=0.0.0.0:${REMOTE_PORT:=9876},server=y"
    echo "Waiting for a debugger at port $REMOTE_PORT..."
fi

if ${QUIET:-false}
then
    exec 2>/dev/null
fi

$LAUNCHER "${OUTPUT_PATH}/${TARGET}/Renode.exe" "${PARAMS[@]:-}"