#!/usr/bin/env bash
set -e
set -u

# this is to support running Renode from external directory
ROOT_PATH="$(cd $(dirname $0); echo $PWD)"

. "$ROOT_PATH/tools/common.sh"

OUTPUT_PATH="$ROOT_PATH/output/bin"

TARGET="Release"
QUIET=false

PARAMS=()
while [[ "$#" -gt 0 ]]
do
    case $1 in
    -q|--quiet)
        QUIET=true
        ;;
    *)
        PARAMS+=("$1")
        ;;
    esac
    shift
done

verify_mono_version

if ${QUIET:-false}
then
    exec 2>/dev/null
fi

$LAUNCHER "${OUTPUT_PATH}/${TARGET}/Renode.exe" "${PARAMS[@]:-}"